name = "Whisper"
uuid = "1846abd0-4e01-46c4-9113-916b63b070ed"
authors = ["Avik Sengupta <avik@sengupta.net> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
